### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by inwtx** [corna/me_cleaner#121]
me_cleaner sets this HAP/AltMeDisable bit when the -s (enable only the kill-switch, but
don't [should be doesn't]
remove the extra code from the firmware)

**Comment by corna** [comment]
I can't understand this issue, can you explain yourself better?

**Comment by Marco01809** [comment]
He is referring to the wiki page [HAP-AltMeDisable-bit](https://github.com/corna/me_cleaner/wiki/HAP-AltMeDisable-bit), but his proposed modification is incorrect.
> me_cleaner sets this HAP/AltMeDisable bit when the -s (enable only the kill-switch, but don't remove the extra code from the firmware)
