### ISSUE TITLE
ASUS PRIME Z270-A 

### ISSUE THREAD

**Issue by bnzis** [corna/me_cleaner#136]
Have someone tried with this motherboard?

**Comment by matt123b** [comment]
The Intel ME firmware and OEM firmware, and the way that both are integrated, can vary greatly from board to board, even within the same board model on different firmware versions. The people that write the BIOS firmware for Intel based motherboards have to work around the ME firmware, as it is a requirement for most post-2006 chipsets. Without all of the firmware or if the ME hardware is broken, it is known that the machine won't boot. So these OEMs usually just won't touch it, with the exception of companies like Purism that are pretty much using ME_cleaner in combination with OEM available one-time hard fuses to disable the ME out of the box. Try it on your machine. If it works it works. If it doesn't work, it doesn't work. Also, BIOS bugs will sometimes prevent ME_cleaner from working properly. On my X230, I had boot hang issues on version 2.68. After updating to 2.70, the issues were resolved. This software is trial and error for the most part.
