### ISSUE TITLE
can't compile me_cleaner

### ISSUE THREAD

**Issue by yoonsikp** [corna/me_cleaner#141]
Please edit the wiki "external flash" so that the line:

```
sudo apt install libpci-dev libusb-dev libusb-1.0
```
comes before

```
make
```
  

Otherwise I can't compile it.

**Comment by persmule** [comment]
Compile what? me_cleaner is a python script that does not need compiling.

**Comment by skochinsky** [comment]
[flashrom](https://github.com/corna/me_cleaner/wiki/External-flashing) I guess?

**Comment by corna** [comment]
If you're referring to flashrom, there's already a link to the official installation page, which lists the requirements. Moreover not every distribution has `apt`.
