### ISSUE TITLE
Does internal oem bios flashing require Intel ME Region Write Access and Intel ME Region Read Access to be enabled?

### ISSUE THREAD

**Issue by laserstrike** [corna/me_cleaner#145]
Me cleaner failed for me using oem bios flashing, but then I read the instructions to internal coreboot flashing and it says that these two settings need to be enabled for it work.

Is the same thing required for oem bios flashing? 
(Mine were disabled, so I'm guessing that's why it didn't work. :( )

By the way, this is the bios for the laptop I tried it on: http://www.dell.com/support/home/us/en/04/Drivers/DriversDetails?driverId=RM8PG

**Comment by corna** [comment]
Which settings?

If you mean the R/W access to the ME region:
IIRC during the power on all the regions can be read/written freely, then the BIOS locks them and they can't be written anymore until the next boot. In this way the BIOS can freely write the updates and then lock the regions.

If you have the ME region locked you can only flash:
 * through the OEM BIOS (but it seems that it's not possible in your case, are the firmware updates signed?)
 * externally

**Comment by laserstrike** [comment]
OK thanks. Yea I've tried flashing the modified file through OEM BIOS
