### ISSUE TITLE
Not working on Asus P7Q57-M DO

### ISSUE THREAD

**Issue by bgermann** [corna/me_cleaner#148]
I tried to clean the ME on an Asus P7Q57-M DO. It has a Q57 (Ibex Peak) chipset and a Core i5 750 (Nehalem) CPU installed. Intel ME 

The board itself has a ME switch, which allows to deactivate Intel ME, which results in the system shutting down after 2 hours uptime. In this operating mode I am able to read/write all flash chip sections with flashrom.

I have tried booting three different cleaned images (without any additional option, with -s and with -S) with ME switch activated, but all result in the same behaviour as with the ME switch deactivated (shutdown after 2 hours).

At the beginning of intelmetool's output I see the error "Bad news, you have a `Q57 Chipset LPC Interface Controller` so you have ME hardware on board and you can't control or disable it, continuing..." - is it impossible to clean ME or do you see any chance of getting it done?

**Comment by corna** [comment]
AFAIK there isn't any 2-hour watchdog in ME (just the 30-minutes one, but recent versions of _me_cleaner_ don't trigger it anymore). That timeout seems enforced by your BIOS: if finds that ME has been disabled by the HDA_SDO switch (so the system is vulnerable, as the flash can be freely written), it turns off forcefully. Unfortunately for you it seems that the AltMeDisable bit or the code removal performed by _me_cleaner_ triggers this check as well.

I'm afraid you're out of luck, unless you know how to disable that watchdog in your BIOS binary.
