### ISSUE TITLE
-d / --descriptor writes wrong bytes

### ISSUE THREAD

**Issue by drujd** [corna/me_cleaner#151]
On some systems, flash read/write permissions are THREE bytes, not two. me_cleaner does not take that into account when using the -d option and writes 0x000404 as ME region permission when it should write 0x044000 (0x004004 converted to little-endian). This results in non-functional rom.

This probably applies to many newer systems (maybe all with 11 ME?) and/or systems with more regions. It could be the cause for #91.

**Comment by corna** [comment]
You're right, [it has changed in Skylake and following](https://review.coreboot.org/11658).
Fixed in 61a70b4112eb6cf420c034dd51ada66e11a32582, thank you for the report.
