### ISSUE TITLE
me_cleaner only working with ME_DISABLE jumper set on the mainboard

### ISSUE THREAD

**Issue by c0d3z3r0** [corna/me_cleaner#154]
Lenovo ThinkStation P320 has a ME_DISABLE jumper on the mainboard.
me_cleaner was called as follows:
`me_cleaner.py -S -r -d -t -M P320_Flash_extractedME.ROM -O P320_Flash_mecleaned.bin P320_Flash.bin `

Output:
Full image detected
The ME/TXE region goes from 0x3000 to 0x800000
Found FPT header at 0x3010
Found 13 partition(s)
Found FTPR header: FTPR partition spans from 0x4000 to 0x133000
Found FTPR manifest at 0x4448
ME/TXE firmware version 11.8.50.3425
Reading partitions list...
 FTPR (0x00001000 - 0x000130000, 0x0012f000 total bytes): NOT removed
 FTUP (0x00272000 - 0x000600000, 0x0038e000 total bytes): removed
 DLMP (      no data here      , 0x00000000 total bytes): nothing to remove
 PSVN (0x00000e00 - 0x000001000, 0x00000200 total bytes): removed
 IVBP (0x0026e000 - 0x000272000, 0x00004000 total bytes): removed
 MFS  (0x00130000 - 0x00026e000, 0x0013e000 total bytes): removed
 NFTP (0x00272000 - 0x00057d000, 0x0030b000 total bytes): removed
 ROMB (      no data here      , 0x00000000 total bytes): nothing to remove
 WCOD (0x0057d000 - 0x0005fd000, 0x00080000 total bytes): removed
 LOCL (0x005fd000 - 0x000600000, 0x00003000 total bytes): removed
 FLOG (0x00600000 - 0x000601000, 0x00001000 total bytes): removed
 UTOK (0x00601000 - 0x000603000, 0x00002000 total bytes): removed
 ISHC (      no data here      , 0x00000000 total bytes): nothing to remove
Removing partition entries in FPT...
Removing EFFS presence flag...
Correcting checksum (0xd0)...
Reading FTPR modules list...
 FTPR.man     (uncompressed, 0x004448 - 0x005180): NOT removed, partition manif.
 rbe.met      (uncompressed, 0x005180 - 0x005216): NOT removed, module metadata
 kernel.met   (uncompressed, 0x005216 - 0x0052a4): NOT removed, module metadata
 syslib.met   (uncompressed, 0x0052a4 - 0x005308): NOT removed, module metadata
 bup.met      (uncompressed, 0x005308 - 0x0058b2): NOT removed, module metadata
 pm.met       (uncompressed, 0x0058b2 - 0x005960): NOT removed, module metadata
 vfs.met      (uncompressed, 0x005960 - 0x0063f8): NOT removed, module metadata
 evtdisp.met  (uncompressed, 0x0063f8 - 0x006586): NOT removed, module metadata
 loadmgr.met  (uncompressed, 0x006586 - 0x0066ae): NOT removed, module metadata
 busdrv.met   (uncompressed, 0x0066ae - 0x006a56): NOT removed, module metadata
 gpio.met     (uncompressed, 0x006a56 - 0x006ba0): NOT removed, module metadata
 prtc.met     (uncompressed, 0x006ba0 - 0x006d50): NOT removed, module metadata
 policy.met   (uncompressed, 0x006d50 - 0x006f12): NOT removed, module metadata
 crypto.met   (uncompressed, 0x006f12 - 0x00709c): NOT removed, module metadata
 heci.met     (uncompressed, 0x00709c - 0x007268): NOT removed, module metadata
 storage.met  (uncompressed, 0x007268 - 0x007564): NOT removed, module metadata
 pmdrv.met    (uncompressed, 0x007564 - 0x007688): NOT removed, module metadata
 maestro.met  (uncompressed, 0x007688 - 0x007772): NOT removed, module metadata
 fpf.met      (uncompressed, 0x007772 - 0x00787e): NOT removed, module metadata
 hci.met      (uncompressed, 0x00787e - 0x007980): NOT removed, module metadata
 fwupdate.met (uncompressed, 0x007980 - 0x007a88): NOT removed, module metadata
 ptt.met      (uncompressed, 0x007a88 - 0x007b94): NOT removed, module metadata
 touch_fw.met (uncompressed, 0x007b94 - 0x007cc0): NOT removed, module metadata
 rbe          (Huffman     , 0x007cc0 - 0x00a3c0): NOT removed, essential
 kernel       (Huffman     , 0x00a3c0 - 0x01a380): NOT removed, essential
 syslib       (Huffman     , 0x01a380 - 0x02d400): NOT removed, essential
 bup          (Huffman     , 0x02d400 - 0x057a00): NOT removed, essential
 pm           (Huffman     , 0x057a00 - 0x05b400): removed
 vfs          (Huffman     , 0x05b400 - 0x068a00): removed
 evtdisp      (Huffman     , 0x068a00 - 0x06b480): removed
 loadmgr      (Huffman     , 0x06b480 - 0x070100): removed
 busdrv       (Huffman     , 0x070100 - 0x073d40): removed
 gpio         (Huffman     , 0x073d40 - 0x075bc0): removed
 prtc         (Huffman     , 0x075bc0 - 0x076ec0): removed
 policy       (Huffman     , 0x076ec0 - 0x081d80): removed
 crypto       (Huffman     , 0x081d80 - 0x09c9c0): removed
 heci         (LZMA/uncomp., 0x09c9c0 - 0x0a08c0): removed
 storage      (Huffman     , 0x0a08c0 - 0x0a6e40): removed
 pmdrv        (Huffman     , 0x0a6e40 - 0x0a8bc0): removed
 maestro      (Huffman     , 0x0a8bc0 - 0x0ada00): removed
 fpf          (Huffman     , 0x0ada00 - 0x0b0340): removed
 hci          (LZMA/uncomp., 0x0b0340 - 0x0b0c00): removed
 fwupdate     (LZMA/uncomp., 0x0b0c00 - 0x0b5940): removed
 ptt          (LZMA/uncomp., 0x0b5940 - 0x0cb000): removed
 touch_fw     (LZMA/uncomp., 0x0cb000 - 0x133000): removed
Relocating FTPR from 0x4000 - 0x133000 to 0x3400 - 0x132400...
 Adjusting FPT entry...
 Moving data...
The ME minimum size should be 360448 bytes (0x58000 bytes)
The ME region can be reduced up to:
 00003000:0005afff me
Setting the HAP bit in PCHSTRP0 to disable Intel ME...
Removing ME/TXE R/W access to the other flash regions...
Extracting and truncating the ME image to "P320_Flash_extractedME.ROM"...
Checking the FTPR RSA signature of the extracted ME image... VALID
Checking the FTPR RSA signature... VALID
Done! Good luck!

The screen stays black, nothing happens. Even the CMOS_RESET jumper does NOT work!
When setting ME_DISABLE jumper the system boots fine.

The system does NOT have Intel BootGuard enabled.

@corna If you are interested I could (privately) share my full flash dump with you.

**Comment by c0d3z3r0** [comment]
Looks like it is the -d parameter... I have to investigate this a bit more

**Comment by corna** [comment]
Are you using the very latest version of me_cleaner? There was a bug with the -d argument on Skylake+, fixed in 61a70b4112eb6cf420c034dd51ada66e11a32582

**Comment by c0d3z3r0** [comment]
Yep, using latest version from master.
fyi CPU is E3-1230v6

**Comment by c0d3z3r0** [comment]
UEFITool output before me_cleaner:
Region access settings:
BIOS: 00Fh 00Ah ME: 00Dh 004h
GbE:  009h 008h EC: 101h 100h
BIOS access table:
      Read  Write
Desc  Yes   No  
BIOS  Yes   Yes
ME    Yes   No  
GbE   Yes   Yes 
PDR   No    No  
EC    No    No  

Output after me_cleaner:
Region access settings:
BIOS: 00Fh 00Ah ME: 004h 004h
GbE:  009h 008h EC: 101h 100h
BIOS access table:
      Read  Write
Desc  Yes   No  
BIOS  Yes   Yes
ME    Yes   No  
GbE   Yes   Yes 
PDR   No    No  
EC    No    No

**Comment by c0d3z3r0** [comment]
@corna I did a simple test: 's/if me11:/if not me11:'. Then the system boots.
I have no clue how those access bits work ;)

**Comment by corna** [comment]
I probably have introduced a regression with that commit.
Can you send me the descriptor of that image? It doesn't contain confidential data (and probably isn't copyrighted, it's just configuration data).

You can extract it with `ifdtool -x image.bin`, send me `flashregion_0_flashdescriptor.bin`

**Comment by c0d3z3r0** [comment]
yep when i‘m back home later, and doing some tests then, too

**Comment by c0d3z3r0** [comment]
I've checked the ifd region, there is no OEM / confidential data so I just put it here.
I think that ME _needs_ to be able to read GbE, Flash and ME regions (to be verified) and stops booting because it cannot read one of them.
That is why using the "not me11" branch works because it enables read access for those three.
The me11 branch only activates read for ME region.
Compare *_ifd_dump.txt

[notme11_ifd_dump.txt](https://github.com/corna/me_cleaner/files/1636777/notme11_ifd_dump.txt)
[mecleaned_ifd_dump.txt](https://github.com/corna/me_cleaner/files/1636778/mecleaned_ifd_dump.txt)
[factory_ifd_dump.txt](https://github.com/corna/me_cleaner/files/1636779/factory_ifd_dump.txt)
[flashdescriptor.bins.zip](https://github.com/corna/me_cleaner/files/1636786/flashdescriptor.bins.zip)

**Comment by c0d3z3r0** [comment]
Yeah. I can confirm my guess.
0x00d004 is the factory setting for access permissions.
me_cleaner sets them to 0x004004 which means only-read for intel me region.
-> The system is stuck
Setting 0x005004 (adding read access for flash descriptor) fixes the problem

Pull request coming in a few minutes ;-)

**Comment by c0d3z3r0** [comment]
#91
#151
