### ISSUE TITLE
An FTPR module named VENOM - ?

### ISSUE THREAD

**Issue by eggalatarian** [corna/me_cleaner#158]
Is within this BIOS  :   https://www.asus.com/Motherboards/P7H55DM_EVO/HelpDesk_BIOS
(BIOS for ASUS P7H55DM_EVO motheboard ; Version 1604 )
` VENOM            (LZMA   , 0x150592 - 0x1523ff       )`
I can't find references to a module with this name.

**Comment by skochinsky** [comment]
AFAIK it was used to interface with Virtualization Engine (VE) -  a sister core for ME that was supposed to implement transparent HDD encryption for the cancelled AT-d (aka Danbury Technology). 

See [2008-vol12-iss-4-intel-technology-journal.pdf](https://www.intel.com/content/dam/www/public/us/en/documents/research/2008-vol12-iss-4-intel-technology-journal.pdf) for more details on how it was planned to work.
