### ISSUE TITLE
setup.py

### ISSUE THREAD

**Issue by daym** [corna/me_cleaner#168]
We've packaged me_cleaner for the Guix System Distribution. For this we always add this file to your 
project:

setup.py with contents:

from setuptools import setup
setup(name='me_cleaner', version='whatever', scripts=['me_cleaner.py'])

Do you want to add it to your project?

**Comment by corna** [comment]
I've added a more complete setup.py, see the `dev` branch.
Can you have a look?

**Comment by daym** [comment]
Yeah, I've read and checked it. It looks and works fine!

Thanks!

**Comment by corna** [comment]
Great, I'll merge it soon into `master`.
