### ISSUE TITLE
me_cleaner doesn't accept the Asus 1015PE BIOS file (1015PE.ROM)

### ISSUE THREAD

**Issue by DebianWall** [corna/me_cleaner#177]
So I tried to apply me_cleaner to the 1015PE BIOS file (it's also the BIOS that the 1011PX uses) but it doesn't accept it, "Unkown image.". Is there a workaround available?

**Comment by skochinsky** [comment]
`me_cleaner` only works on full SPI flash images or ME region images. It won't work on BIOS-only images, update capsules and other formats. You should dump the full flash and use `me_cleaner` on it, that's the only reliable way.

**Comment by DebianWall** [comment]
Mhm, seems I'll need to get an external programmer then since the 1011PX is not supported with flashrom.
