### ISSUE TITLE
Potential Development of FSP replacement?

### ISSUE THREAD

**Issue by flawedworld** [corna/me_cleaner#199]
So these guys were seemingly working on the FSP: https://puri.sm/posts/intel-fsp-reverse-engineering-finding-the-real-entry-point/

I have their code that got taken down, here: https://github.com/flawedworld/IntelFSPLeak

Is this of any use? Not my area really so I might be being just a bit too over the top

**Comment by timofonic** [comment]
@flawedworld I have no idea, but I forked your repo because I'm against censoring. I hope this goes further and some interesting results appear.
