### ISSUE TITLE
External flash on a PLCC-32 ?

### ISSUE THREAD

**Issue by TheSanchezRick** [corna/me_cleaner#205]
Hi everybody :)

I was wondering if it was possible to process the external flash on a computer with a PLCC-32 bios chip (I've only found tutorial for SOIC 8 model) and if so, how to do it ?
![e](https://user-images.githubusercontent.com/39738915/40669824-2128da80-6368-11e8-9db6-fadb1943cc12.jpg)
The chip seems to be soldered on the motherboard, which will probably complicate things.

Thank you in advance
Have a nice day !

**Comment by skochinsky** [comment]
what chipset is it? PLCC is unlikely to have ME since it generally only supports SPI flash.

**Comment by TheSanchezRick** [comment]
Really ? :o This computer has a Intel Celeron D inside, which i assume has a pre-skylake ME version (stored on the external chip) or maybe i'm wrong ?

Thanks for your answer !

**Comment by corna** [comment]
We need more informations:

 * Remove the BIOS label and read the chip's model
 * Run `lspci`

**Comment by platomav** [comment]
There is no Engine on a 2004-2005 platform.

**Comment by corna** [comment]
> There is no Engine on a 2004-2005 platform.

I missed the "Intel Celeron D" part ;)
