### ISSUE TITLE
Does me_cleaner disables the 30 minutes watchdog?

### ISSUE THREAD

**Issue by icceland** [corna/me_cleaner#209]
Hi All,
I had already an me_cleaner  action without positive result. But the whole operation is a case for other topic, which will probably come, after I collect some more information. The fact is I had now i3-3120m CPU left and a Sony Vaio - **Intel hm70** based notebook.
Suprisingly the processor works fine with the "unsupported" chipset. Although with 30 minutes shutdown. 

My question is, if **me_cleaner** is able to disable this shutdown or it just stops the ambiguous ME functionality? In other words, is it worth to dettaching the BIOS chip from the mainboard. It's fragile action and I don't want to risk in hopeles case.

If it's worth, I'llshare my experiences.

Kind regards,
Gregor

**Comment by platomav** [comment]
HM70 worked only with Pentium and Celeron and the restriction was hardcoded in the PCH so afaik no, mc_cleaner won't help you.

**Comment by icceland** [comment]
But after inserting of the CPU 30 minutes works everything perfectly. This reminds me the ME watchdog.

**Comment by platomav** [comment]
It was an artificial limitation to separate the entry level HM70 systems from the mainstream market. Bricking the ME firmware won't help.

**Comment by icceland** [comment]
O.K. So the issue could be clam for closed. Thanks platomav!

**Comment by qnxdev** [comment]
@icceland I have a SONY VAIO with Intel® HM76 Express Chipset

I haven't tried it yet but I wish to.
