### ISSUE TITLE
Compatiblity List

### ISSUE THREAD

**Issue by brianherman** [corna/me_cleaner#218]
I would like to contribute a compatibility list could I create a branch point it to a google doc forum and get reports from your users and update the github repository with a text file and csv?

**Comment by xinterix** [comment]
I assume you looked at or got some information from the list [here](https://github.com/corna/me_cleaner/issues/3), right?

**Comment by skochinsky** [comment]
see also https://github.com/corna/me_cleaner/wiki/me_cleaner-status
