### ISSUE TITLE
Get the status of Intel ME is outdated

### ISSUE THREAD

**Issue by 532910** [corna/me_cleaner#247]
```
$  git clone --depth=1 https://review.coreboot.org/p/coreboot

Cloning into 'coreboot'...
fatal: https://review.coreboot.org/p/coreboot/info/refs not valid: is this a git repository?
```

Please update

**Comment by 532910** [comment]
looks like it should be ```git clone https://github.com/coreboot/coreboot```

**Comment by 532910** [comment]
```git clone https://review.coreboot.org/coreboot.git```
just without ```/p```

**Comment by corna** [comment]
Yep, the coreboot repo link has changed
I've updated the wiki, thanks for the report
