### ISSUE TITLE
Hey, have you seen/tried this? to remove intel me from the x230?

### ISSUE THREAD

**Issue by FrostKnight** [corna/me_cleaner#252]
https://tjheeta.github.io/2018/07/15/thinkpad-x230-coreboot-power-usage/

Can this blog's guide be used to completely delete intel me from the X230?

IF so, let me know, I am very curious.

I would love to have the intel me completely removed from my x230 if possible.

**Comment by zamaudio** [comment]
It is a good guide, but note that it is just using me_cleaner.py to remove *most* of the ME blob, its not completely gone.  I highly recommend doing it though if you own a x230.

**Comment by FrostKnight** [comment]
Okay, then I will close this thread. Seeing as it doesn't do anything special. If you disagree just reopen it.
