### ISSUE TITLE
me_cleaner.py", line 548, in <module>

### ISSUE THREAD

**Issue by ghost** [corna/me_cleaner#266]
Hey Wassup,
I  did almost everything but following error occurs

C:\WINDOWS\system32>C:\Python37\python C:\me_cleaner-master\me_cleaner.py -S -O modified_image.bin original_dump.bin
Traceback (most recent call last):
  File "C:\me_cleaner-master\me_cleaner.py", line 548, in <module>
    f = open(args.file, "rb" if args.check or args.output else "r+b")
FileNotFoundError: [Errno 2] No such file or directory: 'original_dump.bin'

i put 'original_dump.bin' into C:\me_cleaner-master

whats wrong i dunno, pls help me

**Comment by skochinsky** [comment]
you need to either specify the full path to the file, or run the script while in `C:\me_cleaner-master`, not in `C:\WINDOWS\system32`.

**Comment by Diamondinthedirt** [comment]
@skochinsky error "unknown  image"
[
![1](https://user-images.githubusercontent.com/40612026/55606155-3b522d00-5767-11e9-9ecf-e3bca4826d39.jpg)
](url)

**Comment by Diamondinthedirt** [comment]
@skochinsky 
what next [??](url
![2](https://user-images.githubusercontent.com/40612026/55606513-9afd0800-5768-11e9-915d-78657f94a2ae.jpg)
)

**Comment by Diamondinthedirt** [comment]
@skochinsky looks like it worked, but not sure
![3](https://user-images.githubusercontent.com/40612026/55606925-33e05300-576a-11e9-9cf0-a41bff75d880.jpg)

**Comment by Diamondinthedirt** [comment]
... ![4](https://user-images.githubusercontent.com/40612026/55607154-f16b4600-576a-11e9-874c-a2037481fa98.jpg)
