### ISSUE TITLE
Low DRAM frequency output "life after ME_CLEANER" no XMP profiles

### ISSUE THREAD

**Issue by ghost** [corna/me_cleaner#275]
Hello,

Since I flashed modified bios achieved by ME_CLEANER I notice that my system doesnt recognize memory correctly and produce only standard frequency =1333 MHz(single 665 MHz), XMP profiles work only untill power off. 

I assume it may be connected to MRC cold reset feature which depends on ME region somehow .. but I dont understand how... and/or memory thermal management ???

I also use AMIBCP to rework my bios but nothing helps

**Comment by skochinsky** [comment]
ME includes functionality for setting up chipset clocks and so you disable it that might affect all sort of things.
