### ISSUE TITLE
Lenovo x270: power-on with no boot after using -S flag 

### ISSUE THREAD

**Issue by leftishness** [corna/me_cleaner#301]
I was able to successfully write the modified image. The image was modified using only the -S flag. However, at power-on several strange beeps played and the screen remained black indefinitely. I had to reflash the original image to recover my system.

I read issue #156 prior to flashing and attempted to follow the same protocol for my machine. I am unsure what the difference is. I do have Boot Guard enabled. However, I have read in multiple places that this process can still work despite Boot Guard.

I am unsure if I did something wrong or whether there is an issue that exists, since we know it has worked before for an x270. Any support in diagnosing this problem is appreciated.

**Comment by ghost** [comment]
The original image was a backup you made, or a file you downloaded somewhere else?
