### ISSUE TITLE
ASUS Z97-A - Mostly working

### ISSUE THREAD

**Issue by flawedworld** [corna/me_cleaner#314]
Running me_cleaner with -S (Removing ME modules where possible and HAP bit) leaves the board fully functional, however the TPM functionality is lost, and is stuck in 'SUPPORT TURNED OFF' in the BIOS.

Also, removing the CMOS battery causes a reboot loop which is only fixable by a reflash? Bit odd.

Tested on latest beta BIOS 3503 (Which is stable bios + spectre/meltdown patches)

**Comment by czeej** [comment]
I think you might want to add -d as well. 
Your I had similar issues where I could remove network stack from ME. But I believe Dell bios has its' own.

**Comment by ValoWaking** [comment]
See on your FSB speed, is it 99.75 mhz?

**Comment by flawedworld** [comment]
> See on your FSB speed, is it 99.75 mhz?

Sorry for the lateness, but this board has issues with correctly setting an accurate BLCK (This generation of CPU's does not have a FSB technically).

I believe this is down to the quartz clock generator (I think thats the right term) not hitting 100mhz perfectly. Either way its nothing to worry about. It is nothing to do with ME.

**Comment by ValoWaking** [comment]
Do u can create your cpu-z screenshot?

**Comment by ValoWaking** [comment]
BLCK is down to 99.75 because ICC profile is deleted by me_cleaner...
