### ISSUE TITLE
Request for a modded x58 bios with me disabled

### ISSUE THREAD

**Issue by washingleavesandthensome23-434** [corna/me_cleaner#329]
so i am hoping someone can upload an modified bios that has me disabled , i use this modified bios 

https://www.bios-mods.com/forum/Thread-ASUS-RAMPAGE-III-EXTREME-BIOS-V1601-Updated-OROM-MOD

i use the s23 variant

https://drive.google.com/drive/folders/1yom15-bsXEw8WR9bV8sQ3AW3UEsILfB1?usp=sharing

**Comment by washingleavesandthensome23-434** [comment]
and yes i know theres no fully disabling , since it needs certain components in order to boot successfully , but afterwards , as known

**Comment by washingleavesandthensome23-434** [comment]
anybody?

**Comment by Stitch626** [comment]
Do you even have a mei device in your device list? I had a msi x58 board which had no mei device and so no security issues.

PS: Requesting a modded bios via github is a bit rude, isn't it.

**Comment by washingleavesandthensome23-434** [comment]
p.s no it aint lols

anyhow ive been informed that this is an non issue on x58 so all is well
