### ISSUE TITLE
clarifying ME regions for shrinking

### ISSUE THREAD

**Issue by DarkCoridor** [corna/me_cleaner#37]
In [the external flashing](https://github.com/corna/me_cleaner/wiki/External-flashing) doc you describe how to change **layout.txt** from something like:

```
00000000:00000fff fd
**00500000**:007fffff bios
00003000:**004fffff** me
00001000:00002fff gbe
```

to something like:

```
00000000:00000fff fd
**00018000**:007fffff bios
00003000:**00017fff** me
00001000:00002fff gbe
```

What is unclear is how you went from **00500000** to **00018000** in the bios region. The me region is more clear as it is in the previous step. Maybe you can explain or make this more clear to people like me who are not so low level? Would be apreciated.

**Comment by corna** [comment]
In that example I shrinked the ME region by moving the region end to a lower address but, to use the space freed, I also moved the start of the BIOS region to a lower address, one byte after the end of the ME region.

I've updated the doc, is it clear now?
