### ISSUE TITLE
Issue with iGPU on Macbook Pro 9,2 (i7-3520M)

### ISSUE THREAD

**Issue by dandongus** [corna/me_cleaner#370]
After running me_cleaner (with -S) on a dump of the uefi firmware and flashing the output back to the eeprom, the machine boots up fine and the ME is disabled/removed, but there's no "graphics acceleration" in OSX, it's instead running with just software rendering. Flashing back the original image restores full functionality, as one would expect. I'm using the stock apple firmware, not coreboot, so I'm not sure that #367 applies here.

Anyone else have a similar issue or any suggestions for what to try?

**Comment by 490398290** [comment]
macOS won't work without ME firmware. So, if you want to have hardware acceleration i suggest to flash back original firmware.

**Comment by Espionage724** [comment]
ME handles protected audio/video playback (PAVP) for Intel graphics (at least on some platforms, if not all), so if macOS has a hard requirement for HDCP that might be an issue.

> macOS won't work without ME firmware

Do you have any more details about this? What does macOS care about ME specifically? There's a variety of GPU fixes for Hackintosh setups; maybe something from there can be implemented?
