### ISSUE TITLE
`more than one $FPT found`

### ISSUE THREAD

**Issue by Kaiyangshi-Ito** [corna/me_cleaner#405]
When I used me_cleaner to modify my externally flashed image, it says
`more than one $FPT found` and doesn't proceed with neutralizing ME?  I've tried both `-S` and `-s`. How should I resolve this? Thanks.

**Comment by Am0g-us** [comment]
Same issue with PR #384
My image is 
[S5500WB_Orig.bin.gz](https://github.com/corna/me_cleaner/files/12886341/S5500WB_Orig.bin.gz)
