### ISSUE TITLE
DDOSing the ME

### ISSUE THREAD

**Issue by Cyberpangolin** [corna/me_cleaner#41]
Hi!
I've just discovered the Intel ME huge issue, after wondering why my network light were still on when my computer was off...
**Maybe** I have a good idea to get rid -temporary - of it.

If I understood well, it is something quite slow compared to the main computer. So, what if I send it lots of orders to make it crash after booting? Say, 10'000 orders to ask the status of the ME, in 1 second.

The main CPU should be powerful enough to kick out the ME, or at last slow it enough to make it inoperative. 

I'm using an haswell cpu and I cannot offer me the luxury to brick my hardware - but I think this kind of attack would be quite simple, effective and reversible (=no brick)

What do you think of it?

**Comment by corna** [comment]
Hi,

I never checked (none of my PCs has AMT, so I may be wrong) but I think that the reason your network lights are still on can be either Intel AMT (if available on your board) or WOL. Intel AMT can usually be disabled from the BIOS menu (or you can completely remove it by flashing an Intel ME image without AMT, rather safe as they are official images) while WOL can be disabled from the OS (`ethtool` in Linux).

I don't think your solution would work, as Intel ME would probably drop the extra requests and keep running normally, while your main system would be slowed by the huge PCI traffic. The solution implemented by _me_cleaner_ is probably the most clean and safe one, even if it requires a flashing (but we're talking about firmware, so I don't think there can be complete solutions that doesn't involve a modification of the ME firmware or of the BIOS).
