### ISSUE TITLE
intelmetool saying that it didn't work

### ISSUE THREAD

**Issue by stone212** [corna/me_cleaner#44]
This me clean was done with coreboot (make menuconfig) so maybe is a coreboot issue.  Anyway, I installed coreboot with me_cleaner, and compiling seemed to indicate that me was removed.

Then I tested  as explained on the wiki: https://github.com/corna/me_cleaner/wiki/External-flashing
```

$ cd coreboot/util/intelmetool
$ make
# ./intelmetool -s
```

Report: 

```
Bad news.  You have a 'QM67 Express Chipset Family Controller' so you have ME hardware on board and you can't control or disable it continuing...

Error mapping physical memory 0x..... [0x4000] ERRNO=1 Operation not permitted
Could not map MEI PCI device memory
```
And that's it.  I do NOT see 

`ME: Error Code              : Image Failure`
` ME: Progress Phase State    : M0 kernel load`

 So does that mean the me_cleaner didn't work?  Or is this a false negative and should I be posting a success story?  Is there another way to test?

**Comment by corna** [comment]
It doesn't mean anything, the tool failed to retrieve any information. You just have to add `iomem=relaxed` to the kernel parameters, like [here](https://github.com/corna/me_cleaner/issues/30#issuecomment-301193328).

Which kernel version are you using?

**Comment by stone212** [comment]
Ohhhh....  Yes, that worked.  Thank you.  My output from intelmetool now matches what you say it should be on your page here:
https://github.com/corna/me_cleaner/wiki/External-flashing
