### ISSUE TITLE
z77a-gd65 gaming mb completely bricked

### ISSUE THREAD

**Issue by c-h-u-c-k** [corna/me_cleaner#73]
bricked my mb. flash tool is available in bios to reflash but fails to flash me fw on reboot. any suggestions?

**Comment by persmule** [comment]
You can never trust vendor-provided flash method. Please always use external programmer to perform modifications which vendors never want, and make backups with it to recover in case of failure.

**Comment by c-h-u-c-k** [comment]
Nevermind! Microsoft pushed a bad update, it was totally not me_cleaner.
