### ISSUE TITLE
Does updating BIOS overwrites me_cleaner's work?

### ISSUE THREAD

**Issue by kjrew** [corna/me_cleaner#74]
If I update BIOS does it overwrite what me_cleaner have done?
Or does it update just the UEFI's region and doesn't touch ME region?

**Comment by corna** [comment]
Likely, many BIOS updates also contains an Intel ME image, both to update or restore a corrupted ME firmware.

**Comment by kjrew** [comment]
Any way to check if it contains it before updating?

**Comment by skochinsky** [comment]
You can try searching for the `$FPT` signature in the BIOS update, though if you don't find one it does *not* mean it hasn't one (e.g. it could be in a compressed form).

Yes, Lenovo updates usually don't touch the ME (but I guess exceptions are always possible).

**Comment by kjrew** [comment]
ok, thanks!

**Comment by corna** [comment]
UEFI updates are usually compressed, so a string search won't probably give you any result. Luckily Lenovo usually provides good changelogs with its BIOS updates, so you can easily see if they included a ME update.
