### ISSUE TITLE
What's the me_cleaner support status for SPS?

### ISSUE THREAD

**Issue by citypw** [corna/me_cleaner#84]
Hi,

I tested Intel(R) Xeon(R) CPU E3-1230 v5( Skylake) with ASUS P10S-M WS accidentally cu'z I thought it was using MEv11 instead of SPSv4.0. So I want to ask a few questions before further test on more machines. Has anyone tested it on SPSv4.0? What's the differences between SPS and regular ME? Is it run MINIX-based OS also?

Thanks,

**Comment by skochinsky** [comment]
SPS 4.0 is somewhat close to ME11 on the low level (x86 core, Minix-based, $CPD code section layout). It does not include AMT functionality since servers tend to have a dedicated BMC for remote management. Instead it may include Node Manager or Datacenter management functionality (sensor readings/fan control etc.).

**Comment by corna** [comment]
The most recent test on SPS is [this one](https://github.com/corna/me_cleaner/issues/71), however it is on SPSv3, so it could be a completely different situation.

**Comment by citypw** [comment]
@skochinsky Is BMC build based on SPS or it's running on another independent chip? It's really good to know that SPSv4 is close to MEv11 maybe cu'z both of them running on x86. Thanks for pointing out.

@corna Great, there are other test cases for removing code modules from SPS. Thanks.

**Comment by skochinsky** [comment]
BMCs tend to use ARM chips but this depends on board manufacturer. They're often Linux-based.

**Comment by citypw** [comment]
Thanks. That's the info I need.

**Comment by Yannik** [comment]
@citypw I successfully used me_cleaner on SPS4 (see https://github.com/corna/me_cleaner/issues/3#issuecomment-368335041)

**Comment by citypw** [comment]
@Yannik Awesome, I only tested [one machine w/ SPSv4.0](https://github.com/hardenedlinux/hardenedlinux_profiles/tree/master/coreboot) resulted in delayed booting if the SPS was soft disable w/o code module removal. We may need more SPS machines to test. Thanks for the info again!

**Comment by Yannik** [comment]
@citypw Yeah, soft disable only didn't work for me either. I think module removal is the way to go here (that worked for me w/o issue).
