### ISSUE TITLE
MSI JSPI1 and JME1

### ISSUE THREAD

**Issue by IwHy4XnXCM** [corna/me_cleaner#86]
Hi there.

Just taking a look at my motherboard, and I've noticed JSPI1 and JME1 pin headers. According to what people are saying online, the JSPI1 header is a convenient interface for flashing (as you'd assume). As for JME1 though, I am confused whether it is related to Intel ME or not.

Could anybody help me find the [pinout for JSPI1](https://i.imgur.com/hdmLPVj.jpg)? It doesn't match up with the [current pinout I'm looking at](https://www.flashrom.org/MSI_JSPI1).

Thanks.

**Comment by skochinsky** [comment]
JME could be for recovey mode, you could try putting a jumper on it and see if you get different messages on boot and/or in intelmetool output.
JSPI1 pinout looks matching to me with the exception of two extra pins. You can probably confirm it with a multimeter and flash chip's datasheet.

**Comment by corna** [comment]
Is it an MSI? It seems identical to [my JSPI1](https://github.com/corna/me_cleaner/wiki/me_cleaner-on-a-MSI-H110M-ECO#step-1-locate-the-spi-flash-chip).

As suggested by Skochinsky, the JME could be the recovery jumper, which could also allow you to disable the descriptor flash restrictions.

**Comment by IwHy4XnXCM** [comment]
@corna That's the one! Same pinout. Annoyingly my jumper cables are too large to all fit onto the motherboard's header, but at least I know it's possible now. Could make the wiki section for "JSPI1" rather than mobo specific?

**Comment by corna** [comment]
It's probably a proprietary MSI connector but I think a separate wiki page is not needed, I'll just add a note stating that it can be found also on other MSI boards.
