### ISSUE TITLE
AsRock X99E-ITX/ac - Success

### ISSUE THREAD

**Issue by Yethal** [corna/me_cleaner#88]
Pretty straightforward installation overall.

1. Download vendor vios from [here](http://www.asrock.com/mb/Intel/X99E-ITXac/?cat=Download&os=BIOS) (The Instant Flash version)
2. Unzip the downloaded package
3. Run me_cleaner on the extracted file (python path/to/me_cleaner X99EITX3.60) Both the standard procedure and -S flag work
4. Copy the modified bios to a FAT32 formatted USB stick
5. Reboot into UEFI
6. Launch Instant Flash
7. Wait for UEFI to detect the modified BIOS on the USB drive
8. Select the file from the menu
9. Wait for the flashing procedure to finish
10. You're done

**Comment by corna** [comment]
Great!
Please also comment on #3 with a link to this page.
