### ISSUE TITLE
FPT not found

### ISSUE THREAD

**Issue by simonepsp** [corna/me_cleaner#9]
Hi,
I'm trying to deblob the intel ME image of my Thinkpad X230 but the script reports "FPT not found".
I checked with an hex editor and the issue seems related to the $FPT position. The script is looking for "$FPT"on 0x30 but on my Intel ME image it is located on 0x3010...

Fixing the seek to 0x3010 isn't enough 'cause even the FPTR partition is "wrongly" located and the script can't find it.
Thanks for your help

ME Backup rom
![01](https://cloud.githubusercontent.com/assets/11884948/21058032/6a153022-be3c-11e6-982f-d33a2f89e170.jpg)
__________________________
![02](https://cloud.githubusercontent.com/assets/11884948/21058033/6a26023a-be3c-11e6-8087-cb9c38dd9239.jpg)

P.S. I'm sure that the dump is correct. I have already double-checked it. :)

**Comment by corna** [comment]
Hi,

I think you're using the full dump, me_cleaner doesn't support yet the full image
Extract the image before with ifdtool -x, then use me_cleaner on the resulting me region

**Comment by simonepsp** [comment]
Thanks for pointing me out that :)
Unfortunately I still have a problem with the checksum correction:

> Correcting checksum...
Traceback (most recent call last):
  File "me_cleaner.py", line 84, in <module>
    (sum(checksum_bytes) - checksum_bytes[0x1b]) &
TypeError: unsupported operand type(s) for +: 'int' and 'str'

How can I fix it? Thanks

**Comment by corna** [comment]
Try to replace checksum_bytes[0x1b] with unpack("<B", checksum_bytes[0x1b])[0]

**Comment by simonepsp** [comment]
same error. I think the issue regards "sum(checksum_bytes)". Probably it can't sum() a string.

![image](https://cloud.githubusercontent.com/assets/11884948/21072368/2bec80dc-bec0-11e6-9453-d752432336bc.png)

> Correcting checksum...
Traceback (most recent call last):
  File "me_cleaner.py", line 208, in <module>
    (sum(checksum_bytes) - unpack("<B", checksum_bytes[0x1b])[0]) &
TypeError: unsupported operand type(s) for +: 'int' and 'str'

**Comment by simonepsp** [comment]
solved. The script must be run with python 3 to work.

**Comment by corna** [comment]
Yes, as stated in the [shebang](https://github.com/corna/me_cleaner/blob/master/me_cleaner.py#L1)
I'll add a notice in the README
Please add a comment in #3 if it works on your thinkpad
