### ISSUE TITLE
--descriptor fails to POST on Acer Predator Helios 300

### ISSUE THREAD

**Issue by Espionage724** [corna/me_cleaner#91]
Report: https://github.com/corna/me_cleaner/issues/3#issuecomment-343714315

If I use the `--descriptor `flag with me_cleaner and flash the BIOS to my laptop, it doesn't POST. I feel like removing the descriptor could be useful. Anything I could try?

**Comment by corna** [comment]
That's very unusual, `--descriptor` [only removes the RW access of Intel ME to the other flash regions](https://github.com/corna/me_cleaner/blob/master/me_cleaner.py#L683-L685), nothing more. This is probably useless (ME is dead anyways) and shouldn't affect at all the BIOS behaviour, maybe your BIOS checks for the correctness of the descriptor access bits.

In conclusion, nothing to be worried about.
