### ISSUE TITLE
me_cleaner -S results in a slower boot

### ISSUE THREAD

**Issue by MindfulProtons** [corna/me_cleaner#95]
Tested with:
MSI H110M-GAMING
Intel Core i5-6402p
Stock UEFI BIOS

I get a slower boot with an "ME Image is corrupt" or something equivalent seen on the MSI-H110M ECO.
I also get this as output from intelmetool:

>MEI not hidden on PCI, checking if visible
>MEI device not found

**Comment by corna** [comment]
Unfortunately there's no solution, BIOS often waits for Intel ME with a long timeout and, unless you can modify your BIOS, I'm afraid you're out of luck.
